AddressApp Tutorial - Part 7 - exported as .jar-file
Made artifact and exported the app as jar, according tho this tutorial:
https://www.jetbrains.com/help/idea/creating-and-running-your-first-java-application.html

Works, if the following parameter is added to the run-configuration for that jar-file:
--add-modules java.xml.bind

But it doesn't run on a double click of the app...

better would be to do it with maven with dependencies, as shown here:
https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j